default:
  target: dev
  outputs:
    dev:
      type: bigquery
      project: %BQ_PROJECT%
      dataset: %BQ_DATASET%
      location: %BQ_LOCATION%
      method: oauth
      priority: interactive
      threads: 4
      job_retries: 1
      job_execution_timeout_seconds: 300
