version: 2

models:
  - name: test1
    columns:
      - name: col
        tests:
          - not_null
          - unique

  - name: test2
    columns:
      - name: col
        tests:
          - not_null
          - unique